version: "3.8"
services:
  api-gateway:
    image: api-gateway:latest 
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_SERVER_HOST=eureka-server
    networks:
      - microservice-network

networks:
  microservice-network:
    external: true
    name: microservice-network
