version: "3.8"
services:
  learn-service:
    build: .
    container_name: learn-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_SERVER_HOST=eureka-server
      - DB_HOST=postgres-learn-dev
      - DB_NAME=learnservicedb
      - DB_USERNAME=postgres
      - DB_PASSWORD=1111
      - KAFKA_BOOTSTRAP_SERVERS=kafka-shared:9092
    depends_on:
      - eureka-server
    networks:
      - microservice-network

networks:
  microservice-network:
    external: true
    name: microservice-network
